#!/usr/bin/env python3
"""
YouTube Cookie 提取和格式化工具
使用方法：
1. 在Chrome開發者工具中復制cookies數據
2. 將數據貼到 raw_cookies.txt
3. 運行此腳本生成 Netscape 格式的 cookies
"""

import json
import re
from datetime import datetime

def convert_chrome_cookies_to_netscape(raw_cookies_text):
    """將Chrome開發者工具的cookies轉換為Netscape格式"""
    
    # Netscape cookies 格式頭部
    netscape_cookies = [
        "# Netscape HTTP Cookie File",
        "# Generated by YouTube Cookie Extractor",
        "# https://curl.se/rfc/cookie_spec.html",
        ""
    ]
    
    # 解析cookies文本
    lines = raw_cookies_text.strip().split('\n')
    
    for line in lines:
        line = line.strip()
        if not line or line.startswith('#'):
            continue
            
        # 假設格式：name=value; domain=.youtube.com; path=/; expires=...
        try:
            # 提取基本的name=value
            if '=' in line:
                parts = line.split('\t') if '\t' in line else [line]
                name_value = parts[0]
                
                if '=' in name_value:
                    name, value = name_value.split('=', 1)
                    
                    # 生成Netscape格式
                    # domain, domain_specified, path, secure, expires, name, value
                    domain = ".youtube.com"
                    domain_specified = "TRUE"
                    path = "/"
                    secure = "FALSE"
                    expires = "1735689600"  # 2025年底
                    
                    netscape_line = f"{domain}\t{domain_specified}\t{path}\t{secure}\t{expires}\t{name}\t{value}"
                    netscape_cookies.append(netscape_line)
        except Exception as e:
            print(f"跳過無效行: {line} - {e}")
            continue
    
    return '\n'.join(netscape_cookies)

def extract_important_youtube_cookies():
    """生成重要的YouTube cookies模板"""
    important_cookies = [
        "# Netscape HTTP Cookie File",
        "# YouTube Essential Cookies",
        "",
        "# 請替換下面的 YOUR_COOKIE_VALUE 為實際值",
        ".youtube.com\tTRUE\t/\tTRUE\t1735689600\tVISITOR_INFO1_LIVE\tYOUR_VISITOR_INFO_VALUE",
        ".youtube.com\tTRUE\t/\tTRUE\t1735689600\tYSC\tYOUR_YSC_VALUE",
        ".youtube.com\tTRUE\t/\tFALSE\t1735689600\tPREF\tYOUR_PREF_VALUE",
        ".youtube.com\tTRUE\t/\tTRUE\t1735689600\t__Secure-3PSIDCC\tYOUR_PSIDCC_VALUE",
        ".youtube.com\tTRUE\t/\tTRUE\t1735689600\t__Secure-3PSID\tYOUR_PSID_VALUE",
        ".youtube.com\tTRUE\t/\tTRUE\t1735689600\t__Secure-3PAPISID\tYOUR_PAPISID_VALUE",
    ]
    return '\n'.join(important_cookies)

if __name__ == "__main__":
    print("🍪 YouTube Cookie 提取工具")
    print("=" * 50)
    
    # 生成模板
    template = extract_important_youtube_cookies()
    with open("youtube_cookies_template.txt", "w", encoding="utf-8") as f:
        f.write(template)
    
    print("✅ 已生成 youtube_cookies_template.txt")
    print("\n📋 請按以下步驟獲取cookies:")
    print("1. 打開Chrome，訪問 https://www.youtube.com 並登入")
    print("2. 按F12打開開發者工具")
    print("3. 點擊 Application > Cookies > https://www.youtube.com")
    print("4. 找到以下重要cookies的值:")
    print("   - VISITOR_INFO1_LIVE")
    print("   - YSC") 
    print("   - __Secure-3PSIDCC")
    print("   - __Secure-3PSID")
    print("   - __Secure-3PAPISID")
    print("5. 將這些值替換到 youtube_cookies_template.txt 中")
    print("6. 重命名為 youtube_cookies.txt")